### ISSUE TITLE
The font does not apply.

### ISSUE THREAD

**Issue by redoxahmii** [Jamir-boop/minimalisticfox#2]
Do i need to install the font in my system first for the font to work because currently the font does not work for me

**Comment by Jamir-boop** [comment]
Yes you need to install the font. [Its avaible on nerd fonts.](https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/CascadiaCode.zip)
The font should be applied once installed just restart your browser.

**Comment by redoxahmii** [comment]
Works now cheers.
