### ISSUE TITLE
Wrong family font name in chrome.css (?)

### ISSUE THREAD

**Issue by h4rmy** [Jamir-boop/minimalisticfox#3]
I am not exactly sure if thats the case for everyone, but for me to make the font work I had to lookup the font family name in windows settings (win11) and see, that its not "CaskaydiaCove NF", but "CaskaydiaCove Nerd Font". It didnt apply otherwise.

**Comment by Jamir-boop** [comment]
![image](https://github.com/Jamir-boop/minimalisticfox/assets/73477811/c065c630-61ac-4e39-8ab2-8c9f0028828c)

I've explicitly selected the font family `CaskaydiaCove NF`. For more information you can check out their official [repo](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/CascadiaCode). 

I'm suspecting that you haven't installed the font "completely," which is the reason that it doesn't work.
