### ISSUE TITLE
url bar shrinks

### ISSUE THREAD

**Issue by BigBadBodyPillow** [Jamir-boop/minimalisticfox#4]
![image](https://github.com/Jamir-boop/minimalisticfox/assets/119925640/d6cb1bfc-fef6-4c41-af69-74a37b43a2b6)

from what i could find out i think its because of max height 0, idk how to fix though

**Comment by Jamir-boop** [comment]
I haven't been able to reproduce this bug, but I suspect it might be related to the CSS variable `--urlbar-toolbar-height:;`
 in your userChrome.css file. You can try adjusting the value of this variable to see if it resolves the issue.
 Also if it dosen't work tell me how did you installed it and what Firefox version are you using.
 
 
![image](https://github.com/Jamir-boop/minimalisticfox/assets/73477811/6cd97e53-c675-4833-b72e-96ae40c354f8)

**Comment by BigBadBodyPillow** [comment]
firefox dev edition 126.0b3
![image](https://github.com/Jamir-boop/minimalisticfox/assets/119925640/a605563d-2c18-4919-8db5-1fbde18d5ad4)

i installed by going to about:profiles then clicking "Open Folder" on the "Root Directory" under the profile "Profile: dev-edition-default".
then i created a "chrome" folder and cloned "https://github.com/Jamir-boop/minimalisticfox.git"

I did make a few edits though, even if i delete the file that i edited and copy the source "userChrome.css" exactly i get the problem.

it was fine until a firefox update maybe 5ish days ago

this is what i have but i still get the issue with the css file from this repo

```
:root {
  --urlbar_height: 40px;
}
#urlbar:not([focused]) #urlbar-input {
  text-align: center !important;
  /* border: 1px solid #191919 !important; */
  /* border-radius: 5px !important; */
}

/* hide nav-bar */
#nav-bar:not([customizing='true']) {
  min-height: 0px !important;
  max-height: 0px !important;
  margin-top: 0px !important;
  margin-bottom: -0px !important;
  transition: all 100ms ease 0s !important;
  z-index: -5 !important;
}

/* show nav-bar on navigator-toolbox hover/focus */
#navigator-toolbox:hover :-moz-any(#nav-bar),
#navigator-toolbox:focus-within :-moz-any(#nav-bar) {
  border-radius: 5px;
  min-height: var(--urlbar_height) !important;
  max-height: var(--urlbar_height) !important;
  margin-top: 0px !important;
  margin-bottom: calc(var(--urlbar_height) * -1) !important;
  transition: all 100ms ease 0s !important;
  z-index: 5 !important;
  background-color: black !important;
}

/* fix urlbar being too high in ff 74 */
* {
  --urlbar-toolbar-height: var(--urlbar_height) !important;
}

/* tab stuff */
.tab-background {
  /* 5px padding on top and bottom so its 40 total*/
  min-height: 30px !important;
}
.tabbrowser-tab[fadein] {
  max-width: 100vw !important;
}
.tab-text {
  margin: 0 auto !important;
}

/* Center tab icon */
.tab-icon-stack {
  margin-inline-start: auto;
}
.tab-label-container {
  max-width: min-content;
  margin-inline-end: auto;
}

/* Fix empty space between tabs */
.titlebar-spacer[type='pre-tabs'],
.titlebar-spacer[type='post-tabs'] {
  width: 30px !important;
}

/* Keeps the .titlebar-spacer[type="pre-tabs"] and [type="post-tabs"] consistent in all window sizes */
:root:not([sizemode='normal']) .titlebar-spacer[type='pre-tabs'] {
  display: block !important;
}
@media (max-width: 500px) {
  .titlebar-spacer[type='post-tabs'] {
    display: block !important;
  }
}

/* Deactivating stuff to make UI simpler */
.tab-close-button,
#TabsToolbar .toolbarbutton-1,
.titlebar-buttonbox-container {
  display: none !important;
}

/* Cascadya cove font */
* {
  font-family: 'CaskaydiaCove Nerd Font' !important;
}
```

**Comment by Jamir-boop** [comment]
This happens because the "dev" branch is a testing environment that receives constant testing and experimental updates, which are not suitable for this theme.
I recommend using Firefox or Firefox ESR, as that's what this theme was built for.

Also keep in mind that future updates in the dev/nightly builds might also break the theme.

**Comment by BigBadBodyPillow** [comment]
okey thank you
