### ISSUE TITLE
Problem when activating the search bar

### ISSUE THREAD

**Issue by im-izz** [Jamir-boop/minimalisticfox#5]
![image](https://github.com/user-attachments/assets/563d5dbc-9fb9-436c-aa6e-ec8d14daca8f)

**Comment by Jamir-boop** [comment]
I noticed this issue starting with Firefox version 128.0. The theme still works with the current Firefox ESR version, so I recommend using that in the meantime. Unfortunately, I don't have time to fix it for the latest Firefox release at the moment.

**Comment by im-izz** [comment]
no worries dude you made something beautiful and its in my hands now, im recreating it right now just give me some time and will update you with what i came up with.

**Comment by im-izz** [comment]
![firefox_VeH97MBVA1](https://github.com/user-attachments/assets/7622b7fc-ed7d-45ee-bec3-07fe010098ea)
So.. what do you think? My Ultra Minimalist Firefox theme (all problems fixed with floating bars everywhere that are animated too!)

**Comment by im-izz** [comment]
@Jamir-boop I've Forked it and made something amazing with it.
